development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: squid_db_development
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: squid_db_test
  pool: 5
  username: root
  password: root
